# Generated by Django 4.1.5 on 2023-01-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0002_mealitems"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MealDefinition",
        ),
    ]
