# Generated by Django 4.2.7 on 2023-11-29 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0004_alter_mealitems_meal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealitems",
            old_name="foodtype",
            new_name="course",
        ),
    ]
