# Generated by Django 4.1.5 on 2023-01-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="Title",
            new_name="title",
        ),
    ]
