# Generated by Django 4.1.5 on 2023-01-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mealdefinition",
            old_name="meal_type",
            new_name="meal_id",
        ),
    ]
