# Generated by Django 4.1.5 on 2023-01-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_mealtypedefinition"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealtypedefinition",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
