# Generated by Django 4.1.5 on 2023-01-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "mealplannerbasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.mealplannerbasemodel",
                    ),
                ),
                ("menu_date", models.DateField()),
            ],
            bases=("base.mealplannerbasemodel",),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "mealplannerbasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.mealplannerbasemodel",
                    ),
                ),
                (
                    "menu_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menu",
                    ),
                ),
            ],
            bases=("base.mealplannerbasemodel",),
        ),
    ]
