# Generated by Django 4.1.5 on 2023-01-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0002_rename_meal_type_mealdefinition_meal_id"),
        ("food", "0002_rename_food_type_food_food_type_id"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="food_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="food.food"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="meal_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="meal.meal"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="menu.menu"
            ),
        ),
    ]
