# Generated by Django 4.1.5 on 2023-01-17 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food",
                to="food.food",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menuitems",
                to="menu.menu",
            ),
        ),
    ]
