# Generated by Django 4.1.5 on 2023-01-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("meal", "0002_rename_meal_type_mealdefinition_meal_id"),
        ("food", "0002_rename_food_type_food_food_type_id"),
        ("menu", "0002_menuitem_food_id_menuitem_meal_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuMeal",
            fields=[
                (
                    "mealplannerbasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.mealplannerbasemodel",
                    ),
                ),
                (
                    "meal_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meal.meal",
                    ),
                ),
                (
                    "menu_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menu",
                    ),
                ),
            ],
            bases=("base.mealplannerbasemodel",),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
            ),
        ),
        migrations.CreateModel(
            name="MenuMealItem",
            fields=[
                (
                    "mealplannerbasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.mealplannerbasemodel",
                    ),
                ),
                (
                    "food_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="food.food",
                    ),
                ),
                (
                    "menu_meal_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menumeal",
                    ),
                ),
            ],
            bases=("base.mealplannerbasemodel",),
        ),
    ]
