# Generated by Django 4.1.5 on 2023-01-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
        ("menu", "0002_alter_menuitem_food_alter_menuitem_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="foodtype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="food.foodtype",
            ),
        ),
    ]
