# Generated by Django 4.2.7 on 2023-11-29 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_menuitem_foodtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="foodtype",
            new_name="course",
        ),
    ]
