# Generated by Django 4.1.5 on 2023-01-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menumeal_alter_menuitem_menu_id_menumealitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
