# Generated by Django 4.1.5 on 2023-01-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0002_rename_meal_type_mealdefinition_meal_id"),
        ("food", "0002_rename_food_type_food_food_type_id"),
        ("menu", "0004_delete_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menumeal",
            name="meal_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_meals",
                to="meal.meal",
            ),
        ),
        migrations.AlterField(
            model_name="menumeal",
            name="menu_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to="menu.menu",
            ),
        ),
        migrations.AlterField(
            model_name="menumealitem",
            name="food_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_foods",
                to="food.food",
            ),
        ),
        migrations.AlterField(
            model_name="menumealitem",
            name="menu_meal_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="menu.menumeal",
            ),
        ),
    ]
