# Generated by Django 4.1.5 on 2023-01-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_food_food_type_id"),
        ("menu", "0005_alter_menumeal_meal_id_alter_menumeal_menu_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["menu_date"]},
        ),
        migrations.AlterField(
            model_name="menumealitem",
            name="food_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_foods",
                to="food.food",
            ),
        ),
    ]
