# Generated by Django 4.1.5 on 2023-01-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_menu_options_alter_menumealitem_food_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menumealitem",
            old_name="food_id",
            new_name="food",
        ),
    ]
