# Generated by Django 4.2.7 on 2023-12-05 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseDef",
            new_name="Course",
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="fooddef",
            options={"verbose_name": "Food Def", "verbose_name_plural": "Food Defs"},
        ),
    ]
