# Generated by Django 4.2.7 on 2023-11-29 01:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0005_rename_foodtype_mealitems_course"),
        ("menu", "0004_rename_foodtype_menuitem_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodType",
            new_name="Course",
        ),
    ]
