# Generated by Django 4.1.5 on 2023-01-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="food_type",
            new_name="food_type_id",
        ),
    ]
