# Generated by Django 4.2.7 on 2023-12-05 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0002_rename_coursedef_course_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodDef",
            new_name="Food",
        ),
    ]
