# Generated by Django 4.1.5 on 2023-01-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_rename_food_type_food_food_type_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foods",
                to="food.foodtype",
            ),
        ),
    ]
