# Generated by Django 4.2.7 on 2023-12-07 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_rename_fooddef_food"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name": "Food", "verbose_name_plural": "Foods"},
        ),
    ]
