# Generated by Django 4.1.5 on 2023-01-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_food_food_type_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="food_type_id",
            new_name="food_type",
        ),
    ]
