# Generated by Django 4.2.7 on 2023-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_alter_food_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="plural_name",
            field=models.CharField(
                default="<django.db.models.fields.CharField>s", max_length=200
            ),
        ),
    ]
