# Generated by Django 4.2.7 on 2023-12-07 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_course_plural_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="plural_name",
        ),
    ]
