# Generated by Django 4.2.7 on 2023-12-12 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0007_meal_mealitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"verbose_name": "Meal", "verbose_name_plural": "Meals"},
        ),
        migrations.AlterField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                default="admin",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foods",
                to="food.course",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="created_by",
            field=models.ForeignKey(
                default="admin",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="created_by",
            field=models.ForeignKey(
                default="admin",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MealItem",
        ),
    ]
