# Generated by Django 4.2.7 on 2023-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0008_alter_meal_options_alter_course_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="courses",
            field=models.ManyToManyField(to="food.course"),
        ),
    ]
