# Generated by Django 5.0 on 2023-12-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0011_remove_food_course_remove_meal_courses_mealcourses"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="courses",
            field=models.ManyToManyField(through="food.MealCourses", to="food.course"),
        ),
    ]
