# Generated by Django 5.0 on 2023-12-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0013_coursefoods_course_foods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="foods",
        ),
        migrations.AlterField(
            model_name="coursefoods",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="food.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursefoods",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="food.food",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="courses",
            field=models.ManyToManyField(
                blank=True, through="food.MealCourses", to="food.course"
            ),
        ),
    ]
