# Generated by Django 5.0 on 2023-12-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0014_remove_course_foods_alter_coursefoods_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="courses",
            field=models.ManyToManyField(through="food.CourseFoods", to="food.course"),
        ),
    ]
