# Generated by Django 5.0 on 2023-12-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0015_food_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="courses",
            field=models.ManyToManyField(
                blank=True, through="food.CourseFoods", to="food.course"
            ),
        ),
    ]
