# Generated by Django 5.0 on 2023-12-19 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0016_alter_food_courses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["name"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="food",
            options={
                "ordering": ["name"],
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
            },
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={
                "ordering": ["name"],
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
            },
        ),
    ]
