# Generated by Django 5.0 on 2023-12-19 06:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0017_alter_course_options_alter_food_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="food",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
            },
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
            },
        ),
        migrations.AlterField(
            model_name="food",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="foods",
                through="food.CourseFoods",
                to="food.course",
            ),
        ),
    ]
