# Generated by Django 5.0 on 2023-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0018_alter_course_options_alter_food_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="meals",
                through="food.MealCourses",
                to="food.course",
            ),
        ),
    ]
