# Generated by Django 5.0 on 2023-12-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0019_alter_meal_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="courses",
        ),
        migrations.AddField(
            model_name="course",
            name="foods",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                through="food.CourseFoods",
                to="food.food",
            ),
        ),
    ]
